### ISSUE TITLE
Repository isn't public

### ISSUE THREAD

**Issue by kelloggm** [morae/dsd-synthesis#4]
I don't think this repository needs to be private; it's not like someone will copy this work. It's much simpler to setup travis on a public repo (since it's free...), so it would be great if we could make this public. In order to setup travis, I also need admin access to the repo. So if you give me admin access, I can do that, too.

**Comment by morae** [comment]
I've made the repo public, but there's no notion of "admins" for user-owned repos, just the single owner, and collaborators.
